### ISSUE TITLE
Porting nomad and autodiff to ArrayFire

### ISSUE THREAD

**Issue by luong-vinh** [stan-dev/nomad#17]
Does anyone know how hard it is to port to [ArrayFire](https://github.com/arrayfire/arrayfire)? ArrayFire has OpenCL, CUDA and CPU backends and many nice language bindings as well.

**Comment by betanalpha** [comment]
This will be highly nontrivial given the global autodiff stack.  Individual functions could utilize such APIs but it would have to be in a bespoke manner and Nomad is aimed for hardware-independent support.  If anyone is interested fork and give it a try, but for now there won't be any movement in Nomad itself.

**Comment by luong-vinh** [comment]
@betanalpha Thanks a lot for your answer. Maybe, when I have some time to work with Stan, I'll give it a try.
